In [1]:
import pandas as pd
import requests
import plotly.express as px
import datetime

In [2]:
base_url = "https://analytics-api-hg65.onrender.com"
path = "/api/v1/analytics"
url = f"{base_url}{path}"
headers = {
    "content-type": "application/json"
}
params = { 
        'symbol': ['btc', 'eth', 'usdt', 'bnb', 'xrp', 'usdc', 'sol', 'trx', 'zec', 'hype', 'doge', 'xmr', 'wbt', 'rain', 'link','usds', 'ada', 'leo', 'xlm', 'near', 'uni', 'bch', 'usde', 'avax', 'ltc', 'cc', 'dai', 'usd1', 'sui', 'hbar', 'gram', 'shib','tao', 'cro', 'usdg', 'm', 'pyusd', 'xaut', 'okb', 'usyc', 'rlusd', 'buidl', 'btw', 'usdy', 'aave', 'pepe', 'ondo', 'ena', 'mnt', 'pump', 'dot', 'aster', 'paxg', 'wlfi', 'morpho', 'wld', 'icp', 'sky', 'htx', 'usdd', 'arb', 'vvv', 'bgb', 'eursafo', 'u', 'usdgo', 'etc', 'usdf', 'bfusd', 'ake', 'kas', 'pol', 'lit', 'gt', 'pi', 'algo', 'kcs', 'jup', 'bcap', 'qnt', 'atom', 'render', 'jst', 'nexo', 'fil', 'cake', 'eutbl', 'jaaa', 'dash', 'vet', 'inj', 'ustb', 'gho', 'aero', 'ethfi', 'apt', 'stable', 'stx', 'xdc'],
        
        'duration': '1 hour',
        
        'history': '7 days'
}

In [3]:
def get_api_data(url, params, headers):
    try:
        response = requests.get(url=url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
        data = pd.DataFrame(data)
        return data
    except Exception as e:
        st.error(f"API error conexion: {e}")

In [4]:
df = get_api_data(url, params, headers)
df.head()

,bucket,symbol,avg_price,count,market_cap,volume_24h,change_24h
0,2026-09-20T03:00:00Z,aave,136.742500,4,2115904463,256211967.0,-4.33400
1,2026-09-20T03:00:00Z,ada,0.221818,4,8335122465,504113406.0,-3.92403
2,2026-09-20T03:00:00Z,aero,0.640660,4,637757571,55515589.0,-2.53729
3,2026-09-20T03:00:00Z,ake,0.065217,4,1514987737,152743230.0,60.18378
4,2026-09-20T03:00:00Z,algo,0.103651,4,939961390,68685910.0,7.44519

In [ ]:
last_date = df['bucket'].iloc[-1]
df_bubble_chart = df[df['bucket'] == last_date]
df_bubble_chart

fig = px.scatter(df, x="change_24h", y="volume_24h",
	        size="market_cap", color="symbol",
            hover_name="symbol",
            log_y=True,
            size_max=60,
            animation_frame="bucket",  # <-- CREA EL REPRODUCTOR TEMPORAL AUTOMÁTICO
    animation_group="symbol",)
fig.show()

In [6]:
columnas_metricas = ['avg_price', 'market_cap', 'volume_24h', 'change_24h']
df_corr = df[columnas_metricas].corr(method='pearson')
px.imshow(df_corr)
df_corr

            avg_price  market_cap  volume_24h  change_24h
avg_price    1.000000    0.975264    0.441720    0.000627
market_cap   0.975264    1.000000    0.557842    0.000941
volume_24h   0.441720    0.557842    1.000000   -0.002462
change_24h   0.000627    0.000941   -0.002462    1.000000